name: build-dev
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build And Push Dev Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEV_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@7bfdda6ef6839504e3a5b2625ad971b17461a0db # v3.0.0
        with:
          host: github.com
          private-key: ${{ secrets.PRIVATE_SSH_KEY }}
          private-key-name: github-ppk

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.login-ecr.outputs.registry }}/dev-orchestrator:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/dev-orchestrator:latest
          file: dev.Dockerfile
          ssh: default
          push: true
          provenance: false