name: build-dev

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"
      - "prod"
      - "preprod"
# TODO Caching changes are only helpful with self hosted runners
jobs:
#  ShouldRun:
#    runs-on: ubuntu-latest
#    outputs:
#      condition: ${{ steps.condition.outputs.condition }}
#    steps:
#      - id: condition
#        run: |
#          echo ${{ github.ref_name }}
#          echo ${{ github.head_ref }}
#          PATTERN='^v[0-9]+\.[0-9]+\.[0-9]+$'
#          if [[ "${{ github.ref_name }}" = *"main"* ]] || [[ "${{ github.head_ref }}" = *"main"* ]] || [[ "${{ github.ref_name }}" =~ $PATTERN ]] || [[ "${{ github.head_ref }}" =~ $PATTERN ]]; then
#             echo "condition=false" >> $GITHUB_OUTPUT
#             echo false
#          else
#             echo "condition=true" >> $GITHUB_OUTPUT
#             echo true
#          fi

  build_and_push:
    name: Build And Push Dev Image
    runs-on: ubuntu-latest
#    if: ${{ needs.ShouldRun.outputs.condition == 'true' }}
#    needs: [ShouldRun]
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PREPROD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PREPROD_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@7bfdda6ef6839504e3a5b2625ad971b17461a0db # v3.0.0
        with:
          host: github.com
          private-key: ${{ secrets.PRIVATE_SSH_KEY_TYPES_REPO }}
          private-key-name: github-ppk

      - name: Download Go Modules
        run: |
          go env -w GOPRIVATE=github.com/DragonOps-io/*
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          go mod download

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.login-ecr.outputs.registry }}/dev-orchestrator:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/dev-orchestrator:latest
          file: dev.Dockerfile
          ssh: default
          push: true
          provenance: false